spring:
  profiles.active: local

---
spring:
  profiles: local
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1/cities_db
    username: suf
    password: password